### ISSUE TITLE
how to set shouldExtractLiteralValuesFromEnum: true like doc

### ISSUE THREAD

**Issue by SimplyY** [hipstersmoothie/react-docgen-typescript-plugin#14]
how to set shouldExtractLiteralValuesFromEnum: true like doc

it similar not work. and options is given to react-docgen-typescript-plugin not react-docgen-typescript

![image](https://user-images.githubusercontent.com/8455579/93769249-1dbf9e80-fc4d-11ea-9035-e2cbf05ff8ae.png)

**Comment by hipstersmoothie** [comment]
could you provide a reproduction repository?

**Comment by SimplyY** [comment]
yesterday I found this issue is not correct.

real reason is another question https://github.com/styleguidist/react-docgen-typescript/issues/301
