### ISSUE TITLE
Webpack 5

### ISSUE THREAD

**Issue by krainboltgreene** [hipstersmoothie/react-docgen-typescript-plugin#18]
So `react-docgen-typescript-plugin@0.6.2` depends on `react-docgen-typescript-loader@3.7.2`, which depends on `@webpack-contrib/schema-utils@1.0.0-beta.0` which has a peer of `webpack@^3.0.0 || ^4.0.0`.

Normally I'd make a PR to `@webpack-contrib/schema-utils`, but they're on version [`v3.0.0`](https://github.com/webpack/schema-utils/releases/tag/v3.0.0)! Luckily the latest version doesn't have any peers (weird), but there's two breaking versions difference so there's some work to do. I head over to `react-docgen-typescript-loader`, but it's currently archived! So now I'm here, which is a library that is still shipping 0.X.Y, to see what I can do about getting ready for Webpack 5. Thoughts?

**Comment by hipstersmoothie** [comment]
So i've moved the bits of code we used from `react-docgen-typescript-loader` into this plugin #19. I'm not sure if there are any other things that we need to do to make this plugin webpack 5 compatible. Will happily merge any PR you make to fix the issue!

**Comment by krainboltgreene** [comment]
I think we're good!
