### ISSUE TITLE
TS > 4 with npm

### ISSUE THREAD

**Issue by chrisflatley** [hipstersmoothie/react-docgen-typescript-plugin#25]
Should the package.json depedency  include typescript 4? 

Something like:

```
"typescript": "^3 | ^4"
```

Currently I can't install this within by create-react-app project which uses TS 4.0.5 when using npm (7) since it states correctly

```
! Found: typescript@4.0.5
npm ERR! node_modules/typescript
npm ERR!   peer typescript@"~4.0.3" from the root project
npm ERR!   peer typescript@">= 3.x" from react-docgen-typescript-plugin@0.7.0
npm ERR!   node_modules/react-docgen-typescript-plugin
npm ERR!     peer react-docgen-typescript-plugin@"0.7.0" from the root project
npm ERR!   3 more (react-docgen-typescript-plugin, tsutils, react-docgen-typescript)
```

**Comment by hipstersmoothie** [comment]
I thought that >= 3.x would cover any new versions too. If that changes fixes that error feel free to make a PR and i'll merge it ASAP!

**Comment by chrisflatley** [comment]
Me too when I think about it. 

I'll investigate a bit more and PR.

**Comment by chrisflatley** [comment]
Sorry for the time waste - the >= 3.x should be enough to cover it according to the spec (and semver.npmjs.com), so I'm closing this.

I suspect there's something going on, but probably not with this dependency. I just  upgraded to npm 7.1.2 and 7.1.1 - things are behaving differently, but I've dropped back to  React 16 now (due to other similar issues as above) to make everything work.

Perhaps  there's been too much change recently with TS4, React17, CRA4 and NPM7 that everything is still catching up.
