### ISSUE TITLE
Bump react-docgen-typescript dependency to 2.0.0

### ISSUE THREAD

**Issue by yanckst** [hipstersmoothie/react-docgen-typescript-plugin#43]
Hi,

Is it possible to bump `react-docgen-typescript dependency`'s version to `2.0.0`?

### Context

It seems that there's an issue fixed inside `react-docgen-typescript` dependency when using typescript version 4.3

`TypeError: (tag.text || "").trim is not a function`. 

code fix : https://github.com/styleguidist/react-docgen-typescript/issues/356
new version on npm : https://www.npmjs.com/package/react-docgen-typescript

Thanks 🙂

**Comment by michelengelen** [comment]
I will file a PR for this change!

**Comment by ptrhck** [comment]
There is an PR on this https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/42 but not merged yet, unfortunately.
