### ISSUE TITLE
displayName causing __docgenInfo not to be generated

### ISSUE THREAD

**Issue by leepowelldev** [hipstersmoothie/react-docgen-typescript-plugin#51]
Not 100% sure if this is an issue caused by this plugin. But I have a component which has a displayName set differently to the variable name it's assigned to - as it's a sub-component:
```
const Item = () => {...}
Item.displayName = 'List.Item'; 

// or

Item.displayName = 'ListItem'; 
```
And when I used a display name like this then no docgen data gets attached to the component. However if I do either of the following:
```
// Set displayName to match the variable name
const Item = () => {...}
Item.displayName = 'Item'; 

// or have no displayName
const Item = () => {...}
```
Then it works as expected. I'm seeing the problem in Storybook, which seems to read the `__docgenInfo` property this plugin creates, so I don't *think* it's an issue in Storybook, and the [react-docgen playground](https://reactcommunity.org/react-docgen/) doesn't seem to have an issue generating the docs - so I'm assuming it might be this plugin.

Is there anything you can think of in the code that might be causing something like this to happen?

**Comment by Dolinskaya** [comment]
+ same problem

**Comment by otterp012** [comment]
I had the same problem
