### ISSUE TITLE
JSDocs tags (e.g. `@since ×××` etc.)

### ISSUE THREAD

**Issue by konradekk** [hipstersmoothie/react-docgen-typescript-plugin#55]
The `react-docgen-typescript` library passes tags from JSDocs (lines with tokens starting with “at” character) which `react-docgen-typescript-plugin` ignores. This pull request amends this so that `tags` metadata is passed appropriately into the generated code.

I’ve prepared a pull request #53 to merge. Please release it so that it's working also (or predominantly) with `webpack@4` [no problems here I guess] and `react-docgen-typescript@1` [I’ve noticed there’re plans to bump to `@2`] as those are versions I am bound for now in code I maintain.

Thanks in advance for finding some time to deal with this issue!

**Comment by Robbie-Cook** [comment]
Thank you for this, this is not working for me either

**Comment by konradekk** [comment]
@hipstersmoothie bumping

**Comment by chrisregner** [comment]
@hipstersmoothie Can we reopen this? This is still the case.

At the moment, I'll probably workaround this by prepend with undersocre since that's working (e.g.  `_@TODO`.)
