### ISSUE TITLE
TypeError: typescript_1.default.createIdentifier is not a function (ts 5.0.0-beta)

### ISSUE THREAD

**Issue by Jack-Works** [hipstersmoothie/react-docgen-typescript-plugin#78]
`ts.createIdentifier` is deprecated (use `ts.factory.create*` instead).

See: https://github.com/microsoft/TypeScript/issues/51362#issuecomment-1408126388

**Comment by jakebailey** [comment]
This seems to have already been fixed: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/commit/b6b5d0615e666bee3c931b3e1c1d5b490257fcea

(Unless this didn't get them all.)

**Comment by Jack-Works** [comment]
oh, thanks! looks like @storybook/react does not use the latest version of this library

**Comment by Jack-Works** [comment]
they pinned to 1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0 so does not include that change.

**Comment by Jack-Works** [comment]
oh sorry please release a new version on npm

**Comment by Klathmon** [comment]
@Jack-Works It seems like storybook has their own wrapper of this project (called @storybook/react-docgen-typescript-plugin) which is pinned to version `1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0`.

This library is working fine and has been for a while, however the storybook-re-published version is still using an old version without the fix.

https://www.npmjs.com/package/@storybook/react-docgen-typescript-plugin

They list this repo as the source, but this repo says to install it via `react-docgen-typescript-plugin` not `@storybook/react-docgen-typescript-plugin`.

So storybook must re-publish their package, or switch to using the `react-docgen-typescript-plugin` directly

**Comment by codinsonn** [comment]
I'm on Storybook 6 and setting the following in main.js doesn't really seem to do anything, storybook just keeps using it's own fork regardless

```
typescript: {
    reactDocgen: 'react-docgen-typescript-plugin'
  },
```

**Comment by targeral** [comment]
> @Jack-Works It seems like storybook has their own wrapper of this project (called @storybook/react-docgen-typescript-plugin) which is pinned to version `1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0`.
> 
> This library is working fine and has been for a while, however the storybook-re-published version is still using an old version without the fix.
> 
> https://www.npmjs.com/package/@storybook/react-docgen-typescript-plugin
> 
> They list this repo as the source, but this repo says to install it via `react-docgen-typescript-plugin` not `@storybook/react-docgen-typescript-plugin`.
> 
> So storybook must re-publish their package, or switch to using the `react-docgen-typescript-plugin` directly. And it looks like they have a PR open as well (I finally found the forked repo here: [storybookjs#8](https://github.com/storybookjs/react-docgen-typescript-plugin/pull/8)).
> 
> And for anyone having this exact error using storybook with ts-5.0 beta before it's fixed, you can work around it by doing:
> 
> * `npm i --save-dev react-docgen-typescript-plugin` to install this package
> * add this to your `main.js` (or `main.ts`) file for storybook:
> 
> ```ts
>   typescript: {
>     reactDocgen: 'react-docgen-typescript-plugin'
>   },
> ```

It seems that Storybook's ability to generate Typescript APi documents doesn't work. I try:

``` ts
typescript: {
  reactDocgen: 'any-string',
},
```

The problem with upgrading to Typescript 5 is resolved, but the Typescript API documentation functionality is also disabled, which is somewhat similar to the effect of using the `none` option.
