### ISSUE TITLE
v1.0.3 and above have not been published to NPM

### ISSUE THREAD

**Issue by jneander** [hipstersmoothie/react-docgen-typescript-plugin#79]
I need to update to v1.0.5 to account for a bug (#58) that was fixed and published with that version, according to this repo's releases. However, when trying to update, I could not get the version to change from a 1.0.2-canary version. When looking at the npm page for this package, it shows no version above v1.0.2. It looks like the GitHub Action to release might be failing: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/actions/runs/4094827997/jobs/7061430005

**Comment by hipstersmoothie** [comment]
Looks like this is all good now!
